/**
 * Indian States and Cities Data
 * Comprehensive list of all Indian states and their major cities
 */

export interface State {
  code: string;
  name: string;
  cities: string[];
}

export const INDIAN_STATES: State[] = [
  {
    code: "AP",
    name: "Andhra Pradesh",
    cities: [
      "Visakhapatnam",
      "Vijayawada",
      "Guntur",
      "Nellore",
      "Kurnool",
      "Rajahmundry",
      "Tirupati",
      "Kakinada",
      "Kadapa",
      "Anantapur",
      "Eluru",
      "Ongole",
      "Nandyal",
      "Machilipatnam",
      "Adoni",
      "Tenali",
      "Chittoor",
      "Hindupur",
      "Proddatur",
      "Bhimavaram",
      "Madanapalle",
      "Guntakal",
      "Dharmavaram",
      "Gudivada",
      "Srikakulam",
    ],
  },
  {
    code: "AR",
    name: "Arunachal Pradesh",
    cities: [
      "Itanagar",
      "Naharlagun",
      "Tawang",
      "Bomdila",
      "Pasighat",
      "Ziro",
      "Along",
      "Tezu",
      "Daporijo",
      "Anini",
    ],
  },
  {
    code: "AS",
    name: "Assam",
    cities: [
      "Guwahati",
      "Silchar",
      "Dibrugarh",
      "Jorhat",
      "Nagaon",
      "Tinsukia",
      "Tezpur",
      "Bongaigaon",
      "Dhubri",
      "Diphu",
      "North Lakhimpur",
      "Karimganj",
      "Goalpara",
      "Sivasagar",
      "Barpeta",
      "Golaghat",
      "Hailakandi",
      "Mangaldoi",
      "Morigaon",
      "Nalbari",
    ],
  },
  {
    code: "BR",
    name: "Bihar",
    cities: [
      "Patna",
      "Gaya",
      "Bhagalpur",
      "Muzaffarpur",
      "Purnia",
      "Darbhanga",
      "Bihar Sharif",
      "Arrah",
      "Begusarai",
      "Katihar",
      "Munger",
      "Chhapra",
      "Saharsa",
      "Hajipur",
      "Sasaram",
      "Dehri",
      "Bettiah",
      "Motihari",
      "Siwan",
      "Kishanganj",
    ],
  },
  {
    code: "CT",
    name: "Chhattisgarh",
    cities: [
      "Raipur",
      "Bhilai",
      "Bilaspur",
      "Korba",
      "Durg",
      "Rajpur",
      "Raigarh",
      "Jagdalpur",
      "Ambikapur",
      "Dhamtari",
      "Chirmiri",
      "Mahasamund",
      "Kanker",
      "Kawardha",
      "Surajpur",
    ],
  },
  {
    code: "GA",
    name: "Goa",
    cities: [
      "Panaji",
      "Vasco da Gama",
      "Margao",
      "Mapusa",
      "Ponda",
      "Bicholim",
      "Curchorem",
      "Valpoi",
      "Sanguem",
      "Canacona",
    ],
  },
  {
    code: "GJ",
    name: "Gujarat",
    cities: [
      "Ahmedabad",
      "Surat",
      "Vadodara",
      "Rajkot",
      "Bhavnagar",
      "Jamnagar",
      "Gandhinagar",
      "Junagadh",
      "Gandhidham",
      "Anand",
      "Navsari",
      "Morbi",
      "Nadiad",
      "Surendranagar",
      "Bharuch",
      "Mehsana",
      "Bhuj",
      "Porbandar",
      "Palanpur",
      "Valsad",
    ],
  },
  {
    code: "HR",
    name: "Haryana",
    cities: [
      "Faridabad",
      "Gurgaon",
      "Panipat",
      "Ambala",
      "Yamunanagar",
      "Rohtak",
      "Hisar",
      "Karnal",
      "Sonipat",
      "Panchkula",
      "Bhiwani",
      "Sirsa",
      "Bahadurgarh",
      "Jind",
      "Thanesar",
      "Kaithal",
      "Palwal",
      "Rewari",
      "Hansi",
      "Narnaul",
    ],
  },
  {
    code: "HP",
    name: "Himachal Pradesh",
    cities: [
      "Shimla",
      "Mandi",
      "Solan",
      "Dharamshala",
      "Bilaspur",
      "Kullu",
      "Chamba",
      "Una",
      "Hamirpur",
      "Nahan",
      "Palampur",
      "Kangra",
      "Nalagarh",
      "Sundarnagar",
      "Paonta Sahib",
    ],
  },
  {
    code: "JK",
    name: "Jammu and Kashmir",
    cities: [
      "Srinagar",
      "Jammu",
      "Anantnag",
      "Baramulla",
      "Sopore",
      "Kathua",
      "Udhampur",
      "Rajouri",
      "Poonch",
      "Leh",
      "Kargil",
      "Pulwama",
      "Kupwara",
      "Bandipora",
      "Ganderbal",
    ],
  },
  {
    code: "JH",
    name: "Jharkhand",
    cities: [
      "Ranchi",
      "Jamshedpur",
      "Dhanbad",
      "Bokaro Steel City",
      "Hazaribagh",
      "Deoghar",
      "Giridih",
      "Ramgarh",
      "Medininagar",
      "Chaibasa",
      "Gumla",
      "Lohardaga",
      "Pakur",
      "Sahebganj",
      "Simdega",
    ],
  },
  {
    code: "KA",
    name: "Karnataka",
    cities: [
      "Bangalore",
      "Mysore",
      "Hubli",
      "Mangalore",
      "Belgaum",
      "Gulbarga",
      "Davangere",
      "Bellary",
      "Bijapur",
      "Shimoga",
      "Tumkur",
      "Raichur",
      "Bidar",
      "Hospet",
      "Hassan",
      "Udupi",
      "Chitradurga",
      "Kolar",
      "Mandya",
      "Chikmagalur",
    ],
  },
  {
    code: "KL",
    name: "Kerala",
    cities: [
      "Kochi",
      "Thiruvananthapuram",
      "Kozhikode",
      "Thrissur",
      "Malappuram",
      "Kannur",
      "Kollam",
      "Alappuzha",
      "Palakkad",
      "Kottayam",
      "Manjeri",
      "Thalassery",
      "Ponnani",
      "Vatakara",
      "Kanhangad",
    ],
  },
  {
    code: "MP",
    name: "Madhya Pradesh",
    cities: [
      "Indore",
      "Bhopal",
      "Jabalpur",
      "Gwalior",
      "Ujjain",
      "Sagar",
      "Ratlam",
      "Satna",
      "Murwara",
      "Singrauli",
      "Rewa",
      "Dewas",
      "Chhindwara",
      "Shahdol",
      "Khandwa",
      "Morena",
      "Bhind",
      "Guna",
      "Vidisha",
      "Chhatarpur",
    ],
  },
  {
    code: "MH",
    name: "Maharashtra",
    cities: [
      "Mumbai",
      "Pune",
      "Nagpur",
      "Thane",
      "Nashik",
      "Aurangabad",
      "Solapur",
      "Amravati",
      "Kolhapur",
      "Sangli",
      "Jalgaon",
      "Akola",
      "Latur",
      "Ahmednagar",
      "Chandrapur",
      "Parbhani",
      "Ichalkaranji",
      "Jalna",
      "Bhusawal",
      "Panvel",
      "Satara",
      "Beed",
      "Yavatmal",
      "Kamptee",
      "Gondia",
    ],
  },
  {
    code: "MN",
    name: "Manipur",
    cities: [
      "Imphal",
      "Thoubal",
      "Bishnupur",
      "Churachandpur",
      "Ukhrul",
      "Kakching",
      "Lilong",
      "Mayang Imphal",
      "Moirang",
      "Nambol",
    ],
  },
  {
    code: "ML",
    name: "Meghalaya",
    cities: [
      "Shillong",
      "Tura",
      "Jowai",
      "Nongpoh",
      "Williamnagar",
      "Baghmara",
      "Resubelpara",
      "Ampati",
      "Khliehriat",
      "Mairang",
    ],
  },
  {
    code: "MZ",
    name: "Mizoram",
    cities: [
      "Aizawl",
      "Lunglei",
      "Saiha",
      "Champhai",
      "Kolasib",
      "Serchhip",
      "Lawngtlai",
      "Mamit",
      "Khawzawl",
      "Hnahthial",
    ],
  },
  {
    code: "NL",
    name: "Nagaland",
    cities: [
      "Dimapur",
      "Kohima",
      "Mokokchung",
      "Tuensang",
      "Wokha",
      "Zunheboto",
      "Phek",
      "Mon",
      "Kiphire",
      "Longleng",
    ],
  },
  {
    code: "OR",
    name: "Odisha",
    cities: [
      "Bhubaneswar",
      "Cuttack",
      "Rourkela",
      "Berhampur",
      "Sambalpur",
      "Puri",
      "Baleshwar",
      "Bhadrak",
      "Baripada",
      "Balangir",
      "Jharsuguda",
      "Bargarh",
      "Rayagada",
      "Jeypore",
      "Kendujhar",
    ],
  },
  {
    code: "PB",
    name: "Punjab",
    cities: [
      "Ludhiana",
      "Amritsar",
      "Jalandhar",
      "Patiala",
      "Bathinda",
      "Pathankot",
      "Hoshiarpur",
      "Batala",
      "Moga",
      "Abohar",
      "Khanna",
      "Malerkotla",
      "Phagwara",
      "Muktsar",
      "Barnala",
      "Firozpur",
      "Chandigarh",
      "Sangrur",
      "Faridkot",
      "Kapurthala",
    ],
  },
  {
    code: "RJ",
    name: "Rajasthan",
    cities: [
      "Jaipur",
      "Jodhpur",
      "Kota",
      "Bikaner",
      "Ajmer",
      "Udaipur",
      "Bhilwara",
      "Alwar",
      "Bharatpur",
      "Sikar",
      "Pali",
      "Tonk",
      "Hanumangarh",
      "Beawar",
      "Dungarpur",
      "Chittorgarh",
      "Ganganagar",
      "Baran",
      "Churu",
      "Jhunjhunu",
    ],
  },
  {
    code: "SK",
    name: "Sikkim",
    cities: [
      "Gangtok",
      "Namchi",
      "Mangan",
      "Gyalshing",
      "Singtam",
      "Rangpo",
      "Jorethang",
      "Ravangla",
      "Pakyong",
      "Soreng",
    ],
  },
  {
    code: "TN",
    name: "Tamil Nadu",
    cities: [
      "Chennai",
      "Coimbatore",
      "Madurai",
      "Tiruchirappalli",
      "Salem",
      "Tirunelveli",
      "Erode",
      "Vellore",
      "Dindigul",
      "Thanjavur",
      "Tuticorin",
      "Hosur",
      "Kanchipuram",
      "Nagercoil",
      "Karaikudi",
      "Neyveli",
      "Cuddalore",
      "Kumbakonam",
      "Tiruvannamalai",
      "Pollachi",
    ],
  },
  {
    code: "TG",
    name: "Telangana",
    cities: [
      "Hyderabad",
      "Warangal",
      "Nizamabad",
      "Karimnagar",
      "Ramagundam",
      "Khammam",
      "Mahbubnagar",
      "Nalgonda",
      "Adilabad",
      "Siddipet",
      "Mancherial",
      "Sangareddy",
      "Miryalaguda",
      "Jagtial",
      "Peddapalli",
    ],
  },
  {
    code: "TR",
    name: "Tripura",
    cities: [
      "Agartala",
      "Udaipur",
      "Dharmanagar",
      "Kailasahar",
      "Belonia",
      "Khowai",
      "Ambassa",
      "Kumarghat",
      "Sabroom",
      "Teliamura",
    ],
  },
  {
    code: "UP",
    name: "Uttar Pradesh",
    cities: [
      "Lucknow",
      "Kanpur",
      "Agra",
      "Varanasi",
      "Allahabad",
      "Meerut",
      "Ghaziabad",
      "Noida",
      "Bareilly",
      "Aligarh",
      "Moradabad",
      "Saharanpur",
      "Gorakhpur",
      "Faizabad",
      "Jhansi",
      "Muzaffarnagar",
      "Mathura",
      "Rampur",
      "Shahjahanpur",
      "Firozabad",
      "Etawah",
      "Sitapur",
      "Bahraich",
      "Budaun",
      "Banda",
    ],
  },
  {
    code: "UT",
    name: "Uttarakhand",
    cities: [
      "Dehradun",
      "Haridwar",
      "Roorkee",
      "Haldwani",
      "Rudrapur",
      "Kashipur",
      "Rishikesh",
      "Ramnagar",
      "Pithoragarh",
      "Manglaur",
      "Nainital",
      "Mussoorie",
      "Almora",
      "Kotdwara",
      "Udham Singh Nagar",
    ],
  },
  {
    code: "WB",
    name: "West Bengal",
    cities: [
      "Kolkata",
      "Howrah",
      "Durgapur",
      "Asansol",
      "Siliguri",
      "Bardhaman",
      "Malda",
      "Baharampur",
      "Habra",
      "Kharagpur",
      "Shantiniketan",
      "Ranaghat",
      "Haldia",
      "Krishnanagar",
      "Jalpaiguri",
      "Raiganj",
      "Balurghat",
      "Bankura",
      "Chinsurah",
      "Alipurduar",
    ],
  },
  {
    code: "AN",
    name: "Andaman and Nicobar Islands",
    cities: [
      "Port Blair",
      "Diglipur",
      "Mayabunder",
      "Rangat",
      "Car Nicobar",
      "Hut Bay",
      "Bambooflat",
      "Garacharma",
      "Ferrargunj",
      "Prothrapur",
    ],
  },
  {
    code: "CH",
    name: "Chandigarh",
    cities: [
      "Chandigarh",
      "Manimajra",
      "Burail",
      "Daria",
      "Kharar",
      "Zirakpur",
      "Panchkula",
      "Mohali",
    ],
  },
  {
    code: "DN",
    name: "Dadra and Nagar Haveli and Daman and Diu",
    cities: [
      "Daman",
      "Diu",
      "Silvassa",
      "Naroli",
      "Amli",
      "Dadra",
      "Kadaiya",
      "Khanvel",
      "Masat",
      "Rakholi",
    ],
  },
  {
    code: "DL",
    name: "Delhi",
    cities: [
      "New Delhi",
      "Delhi",
      "North Delhi",
      "South Delhi",
      "East Delhi",
      "West Delhi",
      "Central Delhi",
      "Noida",
      "Gurgaon",
      "Faridabad",
    ],
  },
  {
    code: "LD",
    name: "Lakshadweep",
    cities: [
      "Kavaratti",
      "Agatti",
      "Amini",
      "Andrott",
      "Kadmat",
      "Kalpeni",
      "Kiltan",
      "Minicoy",
      "Chetlat",
      "Bitra",
    ],
  },
  {
    code: "PY",
    name: "Puducherry",
    cities: [
      "Puducherry",
      "Karaikal",
      "Mahe",
      "Yanam",
      "Ozhukarai",
      "Villianur",
      "Bahour",
      "Ariyankuppam",
      "Nettapakkam",
      "Mannadipet",
    ],
  },
];

/**
 * Get all state names
 */
export const getStateNames = (): string[] => {
  return INDIAN_STATES.map((state) => state.name);
};

/**
 * Get cities for a specific state
 */
export const getCitiesByState = (stateName: string): string[] => {
  const state = INDIAN_STATES.find((s) => s.name === stateName);
  return state ? state.cities : [];
};

/**
 * Get state code by state name
 */
export const getStateCode = (stateName: string): string | undefined => {
  const state = INDIAN_STATES.find((s) => s.name === stateName);
  return state?.code;
};

